### ISSUE TITLE
Dataset Acquisition

### ISSUE THREAD

**Issue by bugczw** [ilaria-manco/muscaps#1]
Hello, I am doing research on audio caption recently, and I am inspired by your article. Could you provide dataset that you are using in this article? Thanks a lot！

**Comment by bugczw** [comment]
@ilaria-manco  Will the dataset you use be published in the future?

**Comment by ilaria-manco** [comment]
Hi there! Unfortunately I can't share the dataset, but in the [data README](https://github.com/ilaria-manco/muscaps/tree/main/data) you can find some guidance on how to prepare the input data, if you wish to put together a similar dataset yourself. Hope this helps :)
