### ISSUE TITLE
pre-trained weights

### ISSUE THREAD

**Issue by ericguizzo** [ilaria-manco/muscaps#2]
Nice work! It would be great to have the pre-trained weights of the whole muscaps model (not only for the feature extractor). 
Could you please share them? :) 
Thanks in advance

**Comment by ilaria-manco** [comment]
Hi Eric, thank you for your interest in this work. The model was trained on a private dataset, so I can't share the pre-trained weights unfortunately. However I'm currently working on a new public dataset for music captioning and hope to be able to share some MusCaps models trained on this in the future.
